"""Shared constants for workipy."""

DEFAULT_BASE_URL = "https://api.clockify.me/api/v1"
NAGER_DATE_BASE_URL = "https://date.nager.at/api/v3"
DEFAULT_OUT_OF_OFFICE_PROJECT = "Out of office"
HOLIDAY_TASK_NAME = "Public Holiday"
SICK_LEAVE_TASK_NAME = "Sick-Leave"
SPECIAL_LEAVE_TASK_NAME = "Special Leave"
VACATION_TASK_NAME = "Vacation"
DEFAULT_REQUEST_TIMEOUT_SECONDS = 30
MAX_ERROR_PAYLOAD_CHARS = 4096
MAX_API_KEY_FILE_BYTES = 4096
MAX_RESPONSE_PAYLOAD_CHARS = 1_048_576
MAX_WORKSPACES = 200
MAX_USERS = 5_000
MAX_PROJECTS = 5_000
MAX_TASKS = 10_000
MAX_TIME_ENTRIES = 100_000
